#!/bin/bash

source  /opt/mountain/prod/_venv/bin/activate
pushd /opt/mountain/prod
DEFAULT_MODEL_FILEPATH="/opt/mountain/prod/model.tflite" \
  python classify.py --config="/config/configuration.yaml" \
  --enable-posting
