#!/bin/bash

source  /opt/mountain/classify/_venv/bin/activate
pushd /opt/mountain/classify
python main.py \
  --dry-run \
  --local-weights="" \
  --local-tracker-db="" \
  snapshot disk \
  --path=""
